/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mystore;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author ALaa MAHMOUD
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField2.setOpaque(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0, 0));
        jTextField2.setBorder(null);
        jTextField2.setEditable(true);

        jTextField2.setText("User Name");
        jTextField2.setForeground(java.awt.Color.GRAY);

        // متغير يتحقق إذا النص الحالي placeholder
        final boolean[] isUsernamePlaceholder = {true};

        // إزالة النص عند أول كتابة
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (isUsernamePlaceholder[0]) {
                    jTextField2.setText("");
                    jTextField2.setForeground(java.awt.Color.BLACK);
                    isUsernamePlaceholder[0] = false;
                }
            }
        });

        // إعادة النص إذا خرج المستخدم ولم يكتب شيء
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextField2.getText().trim().isEmpty()) {
                    jTextField2.setText("User Name");
                    jTextField2.setForeground(java.awt.Color.GRAY);
                    isUsernamePlaceholder[0] = true;
                }
            }
        });
        jButton1 = new javax.swing.JButton();
        jButton1.setOpaque(false);
        jButton1.setBackground(new java.awt.Color(0, 0, 0, 0));
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField1.setText("Enter Password");
        jPasswordField1.setEchoChar((char) 0);
        jPasswordField1.setForeground(java.awt.Color.GRAY);
        jPasswordField1.setOpaque(false);
        jPasswordField1.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPasswordField1.setBorder(null);

        final boolean[] isPlaceholder = {true};

        // عند الضغط على أي مفتاح
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (isPlaceholder[0]) {
                    jPasswordField1.setText("");
                    jPasswordField1.setEchoChar('●'); // أو '*'
                    jPasswordField1.setForeground(java.awt.Color.BLACK);
                    isPlaceholder[0] = false;
                }
            }
        });

        // لما المستخدم يخرج من الحقل بدون كتابة شيء
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jPasswordField1.getPassword().length == 0) {
                    jPasswordField1.setText("Enter Password");
                    jPasswordField1.setEchoChar((char) 0);
                    jPasswordField1.setForeground(java.awt.Color.GRAY);
                    isPlaceholder[0] = true;
                }
            }
        });
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox1.setBorderPainted(false); 
        jCheckBox1.setFocusPainted(false);  
        jCheckBox1.setContentAreaFilled(false);

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (jCheckBox1.isSelected()) {
                    jPasswordField1.setEchoChar((char) 0);
                } else {
                    jPasswordField1.setEchoChar('●');
                }
            }
        });
        jButton2 = new javax.swing.JButton();
        jButton2.setForeground(java.awt.Color.BLUE);
        jButton2.setBorderPainted(false); 
        jButton2.setFocusPainted(false);  
        jButton2.setContentAreaFilled(false);
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        setSize(new java.awt.Dimension(600, 800));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Snap ITC", 3, 88)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("TOYS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 50, 410, 120);

        jLabel2.setFont(new java.awt.Font("Snap ITC", 3, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 153, 0));
        jLabel2.setText("LAND");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 120, 520, 70);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Segoe UI Light", 0, 40)); // NOI18N
        jTextField2.setForeground(java.awt.SystemColor.controlShadow);
        jTextField2.setToolTipText("");
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(230, 270, 390, 80);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 510, 490, 90);

        jPasswordField1.setFont(new java.awt.Font("Segoe UI Light", 0, 40)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(240, 380, 390, 70);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jCheckBox1.setText("show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(240, 450, 260, 40);

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Forgot Password?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 600, 250, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -70, 1360, 900);
        jLabel1.getAccessibleContext().setAccessibleParent(jLabel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       ResetPasswordFrame resetFrame = new ResetPasswordFrame();
       resetFrame.setVisible(true);
       resetFrame.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = jTextField2.getText();
        String password = new String(jPasswordField1.getPassword());
        
        // Check if fields contain placeholder text
        if (username.equals("User Name") || password.equals("Enter Password")) {
            JOptionPane.showMessageDialog(this, "Please enter both username and password", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
       /** 
        try {
            // Connect to PostgreSQL
            DriverManager.registerDriver(new org.postgresql.Driver());
            String url = "jdbc:postgresql://localhost:5432/postgres";
            String dbUsername = "sami";
            String dbPassword = "123456";
            
            Connection con = DriverManager.getConnection(url, dbUsername, dbPassword);
            Statement stmt = con.createStatement();
            
            // Query to check admin credentials
            String query = "SELECT * FROM admin WHERE username = '" + username + "' AND password = '" + password + "'";
            ResultSet rs = stmt.executeQuery(query);
            
            if (rs.next()) {
                // Login successful
                login login = new login();
                login.setVisible(true);
                login.setLocationRelativeTo(this);
                this.dispose();
            } else {
                // Login failed
                JOptionPane.showMessageDialog(this, "Invalid username or password", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
            
            // Close connections
            rs.close();
            stmt.close();
            con.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }*/
        login login = new login();
                login.setVisible(true);
                login.setLocationRelativeTo(this);
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
